apiVersion: v1
kind: Service
metadata:
  name: {{ include "mumble-server.fullname" . }}-udp
  {{- with .Values.udpService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "mumble-server.labels" . | nindent 4 }}
  {{- with .Values.udpService.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.udpService.type }}
  ports:
    - port: {{ .Values.udpService.port }}
      targetPort: 64738
      protocol: UDP
      name: mumble-udp
  selector:
    {{- include "mumble-server.selectorLabels" . | nindent 4 }}
